version: '3.9'
services: 
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.3
    environment: 
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports: 
      - 9200:9200
    volumes: 
      - ./data:/usr/share/elasticsearch/data
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.13.3
    environment: 
      - elasticsearch.hosts=http://localhost:9200
    ports: 
     - 5601:5601

  # logstash:
  #   container_name: logstash
  #   image: docker.elastic.co/logstash/logstash:7.13.3
  #   volumes:
  #     # - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
  #     # - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
  #     - ./file/test.csv:/usr/share/logstash/data/test.csv
  #     - ./logstash/pipeline/:/usr/share/logstash/pipeline/
  #   ports: 
  #     - 9600:9600
  #   # links:
  #   #   - elasticsearch:elasticsearch
    
